use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.


WriteMakefile(
    'NAME'      => 'Math::Gsl::Sf',
    'VERSION_FROM' => 'Sf.pm', # finds $VERSION
    'LIBS'      => ['-lgsl -lgslcblas -lm'],   # e.g., '-lm' 
    'DEFINE'    => '',     # e.g., '-DHAVE_SOMETHING' 
    'INC'       => '',     # e.g., '-I/usr/include/other' 
);

