# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.

package Math::GSL::Heapsort;
use base qw(Exporter);
use base qw(DynaLoader);
package Math::GSL::Heapsortc;
bootstrap Math::GSL::Heapsort;
package Math::GSL::Heapsort;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Math::GSL::Heapsort;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Math::GSL::Heapsort;

*gsl_heapsort = *Math::GSL::Heapsortc::gsl_heapsort;
*gsl_heapsort_index = *Math::GSL::Heapsortc::gsl_heapsort_index;

# ------- VARIABLE STUBS --------

package Math::GSL::Heapsort;


@EXPORT_OK = qw/
               gsl_heapsort 
               gsl_heapsort_index 
             /;
%EXPORT_TAGS = ( all => [ @EXPORT_OK ] );
1;
