# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.

package Math::GSL::Siman;
use base qw(Exporter);
use base qw(DynaLoader);
package Math::GSL::Simanc;
bootstrap Math::GSL::Siman;
package Math::GSL::Siman;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package Math::GSL::Siman;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Math::GSL::Siman;

*gsl_siman_solve = *Math::GSL::Simanc::gsl_siman_solve;
*gsl_siman_solve_many = *Math::GSL::Simanc::gsl_siman_solve_many;

############# Class : Math::GSL::Siman::gsl_siman_params_t ##############

package Math::GSL::Siman::gsl_siman_params_t;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( Math::GSL::Siman );
%OWNER = ();
%ITERATORS = ();
*swig_n_tries_get = *Math::GSL::Simanc::gsl_siman_params_t_n_tries_get;
*swig_n_tries_set = *Math::GSL::Simanc::gsl_siman_params_t_n_tries_set;
*swig_iters_fixed_T_get = *Math::GSL::Simanc::gsl_siman_params_t_iters_fixed_T_get;
*swig_iters_fixed_T_set = *Math::GSL::Simanc::gsl_siman_params_t_iters_fixed_T_set;
*swig_step_size_get = *Math::GSL::Simanc::gsl_siman_params_t_step_size_get;
*swig_step_size_set = *Math::GSL::Simanc::gsl_siman_params_t_step_size_set;
*swig_k_get = *Math::GSL::Simanc::gsl_siman_params_t_k_get;
*swig_k_set = *Math::GSL::Simanc::gsl_siman_params_t_k_set;
*swig_t_initial_get = *Math::GSL::Simanc::gsl_siman_params_t_t_initial_get;
*swig_t_initial_set = *Math::GSL::Simanc::gsl_siman_params_t_t_initial_set;
*swig_mu_t_get = *Math::GSL::Simanc::gsl_siman_params_t_mu_t_get;
*swig_mu_t_set = *Math::GSL::Simanc::gsl_siman_params_t_mu_t_set;
*swig_t_min_get = *Math::GSL::Simanc::gsl_siman_params_t_t_min_get;
*swig_t_min_set = *Math::GSL::Simanc::gsl_siman_params_t_t_min_set;
sub new {
    my $pkg = shift;
    my $self = Math::GSL::Simanc::new_gsl_siman_params_t(@_);
    bless $self, $pkg if defined($self);
}

sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        Math::GSL::Simanc::delete_gsl_siman_params_t($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package Math::GSL::Siman;


@EXPORT_OK = qw/
               gsl_siman_solve 
               gsl_siman_solve_many 
             /;
%EXPORT_TAGS = ( all => [ @EXPORT_OK ] );
1;
